// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google": {
            "get": {
                "description": "Google Login of the application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Google Login",
                "operationId": "google-login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL to redirect to after successful login (optional, overrides default success redirect URL)",
                        "name": "redirect_url",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Google login URL retrieved successfully. Available code (SUCCESS)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseSwaggerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AuthGoogleLoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid redirect URL provided. Available code (INVALID_REDIRECT_URL)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve Google login URL. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        },
        "/auth/google/callback": {
            "get": {
                "description": "Google Callback for the application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Google Callback",
                "operationId": "google-callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Google",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "State parameter for CSRF protection",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirects to the failure URL with error code as query parameter. Available code (INTERNAL_SERVER_ERROR, INVALID_STATE, PROVIDER_ERROR, TOKEN_EXCHANGE_FAILED, INVALID_CALLBACK, FAILED_CALLBACK)",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "CookieAccessToken": []
                    }
                ],
                "description": "Logout the currently authenticated user by invalidating their session and tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "operationId": "logout",
                "responses": {
                    "200": {
                        "description": "User logged out successfully. Available code (SUCCESS)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - user is not authenticated. Available code (UNAUTHORIZED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAccessToken": []
                    }
                ],
                "description": "Get the currently authenticated user's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Current User",
                "operationId": "get-current-user",
                "responses": {
                    "200": {
                        "description": "Current user retrieved successfully. Available code (SUCCESS)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseSwaggerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AuthMeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized - user is not authenticated. Available code (UNAUTHORIZED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "422": {
                        "description": "User not found. Available code (USER_NOT_FOUND)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "security": [
                    {
                        "CookieRefreshToken": []
                    }
                ],
                "description": "Refresh the access token using a valid refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Access Token",
                "operationId": "refresh-access-token",
                "responses": {
                    "200": {
                        "description": "Access token refreshed successfully. Available code (SUCCESS)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired refresh token. Available code (UNAUTHORIZED, INVALID_REFRESH_TOKEN, REFRESH_TOKEN_NOT_ELIGIBLE[remaining_seconds])",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check Health of the application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check Health",
                "operationId": "check-health",
                "responses": {
                    "200": {
                        "description": "Health check successful. Available code (SUCCESS)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseSwaggerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.HealthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "CookieAccessToken": []
                    }
                ],
                "description": "Get list of users with pagination and search",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "List Users",
                "operationId": "user-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by name (min 3 chars)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "id",
                            "created_at",
                            "name",
                            "email"
                        ],
                        "type": "string",
                        "default": "id",
                        "description": "Order by field",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Sort direction",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "active",
                            "inactive",
                            "banned"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Users fetched successfully. Available code (LIST_FETCHED)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BasePaginationSwaggerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.ListUserResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request. Available code (VALIDATION_ERROR, BAD_REQUEST)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerValidationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. Available code (UNAUTHORIZED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAccessToken": []
                    }
                ],
                "description": "Create a new user. Validation: email REQUIRED, EMAIL, MAX 255; name REQUIRED, ALPHASPACE, MIN 3, MAX 64; avatar REQUIRED, STARTSWITH \"avatar:\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User",
                "operationId": "user-create",
                "parameters": [
                    {
                        "description": "Create User Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully. Available code (CREATED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - invalid input data. Available code (VALIDATION_ERROR, BAD_REQUEST)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerValidationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. Available code (UNAUTHORIZED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        },
        "/user/me/getting-started": {
            "post": {
                "security": [
                    {
                        "CookieAccessToken": []
                    }
                ],
                "description": "Complete the getting started process for the user. Validation:\nname = REQUIRED, ALPHASPACE, MIN 3, MAX 64\navatar = REQUIRED, STARTSWITH \"avatar:\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserMe"
                ],
                "summary": "Getting Started",
                "operationId": "user-me-getting-started",
                "parameters": [
                    {
                        "description": "Getting Started Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserMeGettingStartedRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Getting started process completed successfully. Available code (SUCCESS)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - invalid input data. Available code (VALIDATION_ERROR, BAD_REQUEST)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerValidationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - user not authenticated. Available code (UNAUTHORIZED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity - validation failed. Available code (INVALID_CURRENT_STEP)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAccessToken": []
                    }
                ],
                "description": "Get user detail by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Detail",
                "operationId": "user-detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User detail fetched successfully. Available code (DETAIL_FETCHED)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.BaseSwaggerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.DetailUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request - invalid ID. Available code (INVALID_PARAM_ID)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. Available code (UNAUTHORIZED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "422": {
                        "description": "User not found. Available code (USER_NOT_FOUND)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAccessToken": []
                    }
                ],
                "description": "Update user name and avatar. Validation: name REQUIRED, ALPHASPACE, MIN 3, MAX 64; avatar REQUIRED, STARTSWITH \"avatar:\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User",
                "operationId": "user-update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update User Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated successfully. Available code (UPDATED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - invalid input data. Available code (VALIDATION_ERROR, BAD_REQUEST)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerValidationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. Available code (UNAUTHORIZED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/status/{status}": {
            "post": {
                "security": [
                    {
                        "CookieAccessToken": []
                    }
                ],
                "description": "Update user status (active, inactive, banned). Validation: status must be one of active, inactive, banned",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User Status",
                "operationId": "user-update-status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "active",
                            "inactive",
                            "banned"
                        ],
                        "type": "string",
                        "description": "Status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User status updated successfully. Available code (UPDATED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - invalid status. Available code (INVALID_PATH, VALIDATION_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. Available code (UNAUTHORIZED)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "422": {
                        "description": "User has same status. Available code (USER_HAS_SAME_STATUS)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error. Available code (INTERNAL_SERVER_ERROR)",
                        "schema": {
                            "$ref": "#/definitions/response.BaseSwaggerEmptyResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.CurrentStep": {
            "type": "string",
            "enum": [
                "initial",
                "completed"
            ],
            "x-enum-varnames": [
                "CurrentStepInitial",
                "CurrentStepCompleted"
            ]
        },
        "entity.UserStatus": {
            "type": "string",
            "enum": [
                "active",
                "inactive",
                "banned"
            ],
            "x-enum-varnames": [
                "UserStatusActive",
                "UserStatusInactive",
                "UserStatusBanned"
            ]
        },
        "request.CreateUserRequest": {
            "type": "object",
            "required": [
                "avatar",
                "email",
                "name"
            ],
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "avatar: coding"
                },
                "email": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "rizalarfiyan@plant-factory.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3,
                    "example": "Rizal Arfiyan"
                }
            }
        },
        "request.UpdateUserRequest": {
            "type": "object",
            "required": [
                "avatar",
                "name"
            ],
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "avatar: coding"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3,
                    "example": "Rizal Arfiyan"
                }
            }
        },
        "request.UserMeGettingStartedRequest": {
            "type": "object",
            "required": [
                "avatar",
                "name"
            ],
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "avatar:coding"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3,
                    "example": "Rizal Arfiyan"
                }
            }
        },
        "response.AuthGoogleLoginResponse": {
            "type": "object",
            "properties": {
                "redirect_url": {
                    "type": "string",
                    "example": "https://accounts.google.com/o/oauth2/auth/..."
                }
            }
        },
        "response.AuthMeResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://plant-factory.com/avatar.jpg"
                },
                "current_step": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.CurrentStep"
                        }
                    ],
                    "example": "completed"
                },
                "email": {
                    "type": "string",
                    "example": "rizalarfiyan@plant-factory.com"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "name": {
                    "type": "string",
                    "example": "Rizal Arfiyan"
                },
                "tenants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AuthMeTenantResponse"
                    }
                }
            }
        },
        "response.AuthMeTenantResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "logo": {
                    "type": "string",
                    "example": "https://plant-factory.com/logo.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "Plant Factory"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"read\"",
                        " \"write\"]"
                    ]
                },
                "role": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "response.BasePaginationSwaggerResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "$ref": "#/definitions/response.MessageSwaggerResponse"
                },
                "pagination": {
                    "$ref": "#/definitions/response.PaginationSwaggerResponse"
                }
            }
        },
        "response.BaseSwaggerEmptyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "x-nullable": true,
                    "example": "null"
                },
                "message": {
                    "$ref": "#/definitions/response.MessageSwaggerResponse"
                }
            }
        },
        "response.BaseSwaggerResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "$ref": "#/definitions/response.MessageSwaggerResponse"
                }
            }
        },
        "response.BaseSwaggerValidationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "x-nullable": true,
                    "example": "null"
                },
                "message": {
                    "$ref": "#/definitions/response.MessageSwaggerValidationResponse"
                }
            }
        },
        "response.DetailUserResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "avatar: coding"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "current_step": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.CurrentStep"
                        }
                    ],
                    "example": "completed"
                },
                "email": {
                    "type": "string",
                    "example": "rizalarfiyan@plant-factory.com"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "is_super_admin": {
                    "type": "boolean",
                    "example": false
                },
                "last_logged_in_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "name": {
                    "type": "string",
                    "example": "Rizal Arfiyan"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.UserStatus"
                        }
                    ],
                    "example": "active"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "response.HealthResponse": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string",
                    "example": "production"
                },
                "name": {
                    "type": "string",
                    "example": "BE Plant Factory"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-01T00:00:00Z"
                }
            }
        },
        "response.ListUserResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "avatar: coding"
                },
                "email": {
                    "type": "string",
                    "example": "rizalarfiyan@plant-factory.com"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "name": {
                    "type": "string",
                    "example": "Rizal Arfiyan"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.UserStatus"
                        }
                    ],
                    "example": "active"
                }
            }
        },
        "response.MessageSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "APP_CODE"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key": "value"
                    }
                }
            }
        },
        "response.MessageSwaggerValidationResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/response.ValidationErrorFieldSwaggerResponse"
                    }
                }
            }
        },
        "response.PaginationSwaggerResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "response.ValidationErrorFieldSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_CODE"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key": "value"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAccessToken": {
            "type": "apiKey",
            "name": "access_token",
            "in": "cookie"
        },
        "CookieRefreshToken": {
            "type": "apiKey",
            "name": "refresh_token",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BE Plant Factory API",
	Description:      "This is an API documentation of BE Plant Factory.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
